import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { autoGenerateDefineConstants } from './scripts/env-auto-loader'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

export default defineConfig(({ mode }) => {
  const platform = process.env.BUILD_PLATFORM || 'web'
  const envDir = fs.existsSync(path.resolve(__dirname, 'env')) ? 'env' : '.'

  let envConstants: Record<string, string> = {}
  try {
    envConstants = autoGenerateDefineConstants(mode)
  } catch (e) {
    console.warn('Env loader warning:', e)
  }

  const env = loadEnv(mode, envDir, '')
  const rawEnv: any = {}
  Object.keys(envConstants).forEach((key) => {
    if (key.startsWith('process.env.')) {
      const pureKey = key.replace('process.env.', '')
      rawEnv[pureKey] = JSON.parse(envConstants[key])
    }
  })

  return {
    server: {
      port: 3000,
      host: '0.0.0.0',
      open: true,
      hmr: { overlay: false },
    },
    envDir,
    plugins: [react()],
    define: {
      ...envConstants,
      'process.env': {
        ...rawEnv,
        NODE_ENV: JSON.stringify(mode),
        APP_NEED_AUTH: JSON.stringify(env.APP_NEED_AUTH || 'true'),
        APP_USE_MOCK: JSON.stringify(env.APP_USE_MOCK || 'true'),
        APP_NAME: JSON.stringify(env.APP_NAME || 'Flux'),
      },
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    build: {
      outDir: `dist/${platform}`,
      sourcemap: mode !== 'production',
      target: 'es2020',
      cssCodeSplit: true,
    },
  }
})
