import { existsSync, readFileSync } from 'fs'
import { join, resolve, dirname } from 'path'
import * as dotenv from 'dotenv'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const PROJECT_ROOT = resolve(__dirname, '..')

/**
 * 核心环境变量加载器
 */
export function enhancedAutoLoadEnvConfig(platformOverride?: string, modeOverride?: string): Record<string, string> {
  const rootDir = PROJECT_ROOT
  const envDir = existsSync(join(rootDir, 'env')) ? join(rootDir, 'env') : rootDir
  
  let targetPlatform = 'web'
  if (platformOverride) {
    targetPlatform = platformOverride
  } else {
    const buildPlatform = (process.env as any).BUILD_PLATFORM
    targetPlatform = buildPlatform || 'web'
  }
  
  const nodeEnv = modeOverride || process.env.NODE_ENV || 'development'
  
  const patterns = [
    '.env',
    '.env.local',
    `.env.${nodeEnv}`,
    `.env.${nodeEnv}.local`,
    `.env.${targetPlatform}`,
    `.env.${targetPlatform}.local`,
    `.env.${nodeEnv}.${targetPlatform}`,
    `.env.${nodeEnv}.${targetPlatform}.local`,
  ]

  const envVars: Record<string, string> = {}
  
  patterns.forEach(pattern => {
    const envPath = join(envDir, pattern)
    if (existsSync(envPath)) {
      const result = dotenv.config({ path: envPath, override: true })
      if (!result.error && result.parsed) {
        Object.assign(envVars, result.parsed)
      }
    }
  })

  // 兜底默认值
  if (!envVars.APP_USE_MOCK) envVars.APP_USE_MOCK = 'true'
  if (!envVars.APP_NEED_AUTH) envVars.APP_NEED_AUTH = 'true'
  if (!envVars.APP_NAME) envVars.APP_NAME = 'Flux'

  // 同步到 Node 进程环境
  Object.assign(process.env as any, envVars)
  
  return envVars
}

/**
 * 为构建工具生成 DefineConstants
 */
export function autoGenerateDefineConstants(modeOverride?: string): Record<string, string> {
  // 获取加载好的环境变量
  const envVars = enhancedAutoLoadEnvConfig(undefined, modeOverride)
  
  let packageVersion = '1.0.0'
  try {
    const pkgPath = join(PROJECT_ROOT, 'package.json')
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
      packageVersion = pkg.version
    }
  } catch (e) {}

  const buildNumber = (process.env as any).BUILD_NUMBER || Math.floor(Date.now() / 1000).toString().slice(-6)
  const SAFE_PREFIXES = ['APP_', 'VITE_', 'TARO_', 'PUBLIC_', 'CAP_']
  
  // 关键：显式指定 Record 类型，解决 TS 索引报错
  const finalEnvVars: Record<string, string> = { 
    ...envVars,
    APP_PUBLIC_VERSION: packageVersion, 
    APP_DISPLAY_VERSION: `${packageVersion} (${buildNumber})`
  }

  const defineConstants: Record<string, string> = {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || modeOverride || 'development'),
    'process.env.BUILD_TIME': JSON.stringify(new Date().toISOString()),
    'process.env.BUILD_PLATFORM': JSON.stringify((process.env as any).BUILD_PLATFORM  || 'web'),
  }

  // 遍历并注入符合前缀的变量
  for (const key in finalEnvVars) {
    if (SAFE_PREFIXES.some(prefix => key.startsWith(prefix))) {
      // 强制使用 (finalEnvVars as any)[key] 避开 TS 严格校验
      defineConstants[`process.env.${key}`] = JSON.stringify((finalEnvVars as any)[key])
    }
  }

  return defineConstants
}

export default autoGenerateDefineConstants